# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.


---
conf.py:
  copyright: 2021
  project: File Canonical
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - file_canonical.tex
    - 'File Canonical'
    - Armin Vieweg
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
